Banco/Models/Cuenta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Models
{
    public class Cuenta
    {
        public int IdCuenta { set; get; }
        [Required]
        public string Nombre { set; get; }
        [Required]
        public string Categoria { set; get; }
        [Required]
        public int SaldoInicial { set; get; }
        [Required]
        public int LimiteCuenta { set; get; }
    }
}

Banco/Models/ErrorViewModel.cs
using System;

namespace WebApplication3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Banco/Models/Transaccion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Models
{
    public class Transaccion
    {
        public int IdTransaccion { set; get; }
        public int IdCuenta { set; get; }
        public string Fecha { set; get; }
        public string Descripcion { set; get; }
        public int Monto { set; get; }
        public bool Tipo { set; get; }
        public Cuenta Cuenta { set; get; }
    }
}

Banco/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.DB;
using WebApplication3.Models;
using WebApplication3.Repo;

namespace WebApplication3.Controllers
{
    public class CuentaController : Controller
    {
        private ICuentarepo context;
        public CuentaController(ICuentarepo context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var cuenta = context.GetCuentas();

            return View("Index", cuenta);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categoria = GetCategorias();
            return View("Create", new Cuenta());
        }
        [HttpPost]
        public IActionResult Create(Cuenta cuenta)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categoria = GetCategorias();
                return View("Create", cuenta);
            }

            cuenta.LimiteCuenta = cuenta.SaldoInicial;

            context.SaveCuenta(cuenta);
            return RedirectToAction("Index");
        }
        private List<String> GetCategorias()
        {
            return new List<string>
            {
                "Propia","Credito"
            };
        }
    }
}

Banco/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication3.DB;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {

        public ViewResult Index()
        {
            return View();
        }

    }
}

Banco/Controllers/TransaccionController.cs
using System;
using System.Collections.Generic;

using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication3.DB;
using WebApplication3.Models;
using WebApplication3.Repo;

namespace WebApplication3.Controllers
{
    public class TransaccionController : Controller
    {
        private ITransaccionrepo context;
        public TransaccionController(ITransaccionrepo context)
        {
            this.context = context;
        }

        public IActionResult Index(int IdCuenta)
        {
            var transacciones = context.GetTransaccions(IdCuenta);
            return View("Index", transacciones);
        }
        [HttpGet]
        public IActionResult Create(int IdCuenta)
        {
            ViewBag.Cuenta = context.GetCuenta(IdCuenta);

            return View("Create", new Transaccion());
        }
        [HttpPost]
        public IActionResult Create(Transaccion transaccion)
        {
            var a = verificarCambios(transaccion);
            if (a == false)
                ModelState.AddModelError("Ingreso", "No se puede gastar lo que no se tiene");

            if (!ModelState.IsValid)
            {
                ViewBag.Cuenta = context.GetCuenta(transaccion.IdCuenta);

                return View("Create", transaccion);
            }
            transaccion.Fecha = DateTime.Now.ToString();
            context.SaveTransaccion(transaccion);
            
            return RedirectToAction("Index", new { transaccion.IdCuenta});
        }

        private bool verificarCambios(Transaccion transaccion)
        {
            var cuenta = context.GetCuenta(transaccion.IdCuenta);
            bool a = true;

            if (transaccion.Tipo == true) {
                cuenta.SaldoInicial += transaccion.Monto;
            }
            else if (transaccion.Tipo == false)
            {
                if (cuenta.LimiteCuenta < transaccion.Monto)
                {
                    a = false;
                    return a;
                }
                else
                {
                    cuenta.SaldoInicial -= transaccion.Monto;
                }
            }
            
            //context.Entry(cuenta).State = EntityState.Modified;
            //context.SaveChanges();
            return a;
        }
    }
}

Banco/Views/Cuenta/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<br />
<form action="/cuenta/create" method="post">
    <div class="form-group">
        <label>Ingresar Nombre de Cuenta</label>
        <input type="text" class="form-control" name="Nombre" value="@Model.Nombre"/>
        @Html.ValidationMessage("Nombre")
    </div>

    <div class="form-group">
        <label>Categoria</label>
        <select class="form-control" name="Categoria">
            <option>-- Seleccione Valor --</option>
            @foreach (var item in ViewBag.Categoria)
            {
                <option value="@item">@item</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label>Ingrese Saldo Inicial </label>
        <input type="text" class="form-control" name="SaldoInicial" value="@Model.SaldoInicial"/>
        @Html.ValidationMessage("SaldoInicial")
    </div>
    <br />
    <div align="center">
        <button class="btn btn-success">Guardar</button>
    </div>
</form>

Banco/Views/Cuenta/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<br />
<div align="right">
    <a href="/cuenta/create" class="btn btn-primary">Crear cuenta</a>
</div>
<br />

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Categoria</th>
            <th>Le queda</th>
            <th>Limite de credito</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nombre</td>
                <td>@item.Categoria</td>
                <td>@item.SaldoInicial</td>
                @if (item.Categoria == "Credito")
                {
                    <td>@item.LimiteCuenta</td>
                }
                else
                {
                    <td></td>
                }
                <td><a href="/transaccion/create?IdCuenta=@item.IdCuenta">Crear transacción</a></td>
                <td><a href="/transaccion/index?IdCuenta=@item.IdCuenta">Mis transacciones</a></td>
            </tr>
        }
    </tbody>
</table>

Banco/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Banco/Views/Home/View.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

Banco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Banco</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Banco</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Index">Cuentas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" id="Correcto">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Banco - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Banco/Views/Transaccion/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<br />
<form action="/transaccion/create" method="post">

    <input type="hidden" name="IdCuenta" value="@ViewBag.Cuenta.IdCuenta" />

    <div class="form-group">
        <label>Descripcion </label>
        <input type="text" class="form-control" name="Descripcion" value="@Model.Descripcion" />
    </div>
    <br />
    <div class="form-group">
        <label>Monto </label>
        <input type="text" class="form-control" name="Monto" value="@Model.Monto" />
    </div>
    <br />
    @if (ViewBag.Cuenta.Categoria == "Propia")
    {
        <div class="form-group">
            <label>Ingreso(T)/Gasto(F) </label>
            <input type="checkbox" name="Tipo" value="true" />
        </div>
    }
    else
    {
        <input type="hidden" name="Tipo" value="false" />
    }

    <div align="center">
        <button class="btn btn-success">Guardar</button>
    </div>
</form>

Banco/Views/Transaccion/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <thead>
        <tr>
            <th>Cuenta</th>
            <th>Fecha de Transaccion</th>
            <th>Descripcion</th>
            <th>Monto</th>
            <th>Tipo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Cuenta.Nombre</td>
            <td>@item.Fecha</td>
            <td>@item.Descripcion</td>
            <td>@item.Monto</td>

            @if (item.Tipo == true)
            {
                <td>Ingreso</td>
            }
            else
            {
                <td>Gasto</td>
            }

        </tr>
        }
    </tbody>
</table>